i enjoy solve it, thank you
Tuwaiq-jed-kot2/HW-Week2_Day03_Inheritance_and_ClassTypes pull request #12
Opened 2021-10-19 21:04 UTC by BashayerH

2021-10-19 22:00 UTC, shuruqt1000 requested changes

2021-10-19 22:00 UTC, shuruqt1000 commented on .idea/Shape.kts
> +        return crPi * (crRadius * crRadius)
why no comment here ?

2021-10-20 06:18 UTC, BashayerH commented on .idea/Shape.kts
> +        return crPi * (crRadius * crRadius)
هنا سويت اوفر رايد للدالة الموجودة في السوبر وغيرت عليها بحيث ترجعلي حساب الدائرة
والباي خليتها اوفر رايد كمان

2021-10-20 06:44 UTC, shuruqt1000 commented
great comments 
good job 
completed

2021-10-20 06:44 UTC, closed without merging