solved :)
Tuwaiq-jed-kot2/HW-Week2_Day03_Inheritance_and_ClassTypes pull request #2
Opened 2021-10-19 14:34 UTC by RajwaAbdulaziz

2021-10-19 21:50 UTC, shuruqt1000 requested changes

2021-10-19 21:50 UTC, shuruqt1000 commented on Circle.kt
> +        print("Circle area = ")
why is it important to override these functions  ?

2021-10-20 06:29 UTC, RajwaAbdulaziz commented on Circle.kt
> +        print("Circle area = ")
So each class can compute their own area according to the specified equation

2021-10-20 06:32 UTC, shuruqt1000 commented
great comments  !!
completed

2021-10-20 06:32 UTC, closed without merging