Week2_Day03_Inheritance_and_ClassTypes
Tuwaiq-jed-kot2/HW-Week2_Day03_Inheritance_and_ClassTypes pull request #21
Opened 2021-10-20 04:29 UTC by Nayf-S-ALzahrani

Week2_Day03_Inheritance_and_ClassTypes

2021-10-20 06:46 UTC, shuruqt1000 requested changes

2021-10-20 06:46 UTC, shuruqt1000 commented on src/homework2.kt
> +        shapeColor = ""
why did you initiate these values ?

2021-10-20 06:46 UTC, shuruqt1000 commented on src/homework2.kt
> +        shapeName= "Circle"
why did you override this ?

2021-10-20 20:46 UTC, Nayf-S-ALzahrani commented on src/homework2.kt
> +        shapeColor = ""
They are only initial values, and the values ​​will be assigned by the functions of the shapes.

2021-10-20 20:46 UTC, Nayf-S-ALzahrani commented on src/homework2.kt
> +        shapeName= "Circle"
Because I'll give its values ​​inside each function.

2021-10-21 10:51 UTC, shuruqt1000 commented
completed

2021-10-21 10:51 UTC, closed without merging