)=
Tuwaiq-jed-kot2/HW-Week2_Day03_Inheritance_and_ClassTypes pull request #22
Opened 2021-10-20 05:10 UTC by BashayrYahya

2021-10-20 06:15 UTC, BashayrYahya commented
..

2021-10-20 06:58 UTC, shuruqt1000 requested changes

2021-10-20 06:58 UTC, shuruqt1000 commented on README.md
> +         return ((height * base) / 2)
where did you use this ?

2021-10-20 06:58 UTC, shuruqt1000 commented on README.md
> +
where did you use these value

2021-10-20 06:58 UTC, shuruqt1000 commented on README.md
> +var shapeColor: String
why did you make this open ?

2021-10-21 12:02 UTC, BashayrYahya commented on README.md
> +var shapeColor: String
to inherits from super class (shape)

2021-10-25 06:26 UTC, shuruqt1000 commented
complete

2021-10-25 06:26 UTC, closed without merging