.
Tuwaiq-jed-kot2/HW-Week2_Day03_Inheritance_and_ClassTypes pull request #8
Opened 2021-10-19 19:57 UTC by Rwan19

2021-10-19 21:22 UTC, shuruqt1000 commented
see comment and fix

2021-10-19 22:16 UTC, shuruqt1000 requested changes
please explain your code do not restate the sentences, I mean explain what values are passes or inherited why use open class in each part if use why is it important and how it affect the rest of the code

2021-10-19 22:16 UTC, shuruqt1000 commented on .idea/libraries/shape1
> +        return x+y
what's are these for ? uncommented code

2021-10-19 22:16 UTC, shuruqt1000 commented on .idea/libraries/shape1
> +        println(" the area of Rectangle is:")
uncommented

2021-10-19 22:16 UTC, shuruqt1000 commented on .idea/libraries/shape1
> +        println(" the area of Circle is:$result")
uncommented

2021-10-19 22:16 UTC, shuruqt1000 commented on .idea/libraries/shape1
> +        return result
why do override explain you code in comment

2021-10-20 10:32 UTC, Rwan19 commented on .idea/libraries/shape1
> +        return x+y
// fun to calculat the area of other class and return the area
  // i use open with function to i can use it in other class and modifcation on value

2021-10-20 10:33 UTC, Rwan19 commented on .idea/libraries/shape1
> +        println(" the area of Rectangle is:")
//function to calculate an area of triangle
 // the function is inhertied from fun computeAreain suberclass i use overrideto allwe to editt modifcation on value

2021-10-20 10:35 UTC, Rwan19 commented on .idea/libraries/shape1
> +        println(" the area of Rectangle is:")
by this equation
 Rectangle area = height times width  (A = h * w)

2021-10-20 10:38 UTC, Rwan19 commented on .idea/libraries/shape1
> +        println(" the area of Circle is:$result")
//i creat variable to store the value of the equation on it
// the function is inhertied from fun computeAreain suberclass i use overrideto hey ward allwe to editt modifcation on value

2021-10-20 10:39 UTC, Rwan19 commented on .idea/libraries/shape1
> +        println(" the area of Circle is:$result")
key ward

2021-10-20 10:41 UTC, Rwan19 commented on .idea/libraries/shape1
> +        return result
overrid is key ward
the function is inhertied from fun computeAreain in suberclass i use overrideto key ward allowed to editt modifcation on value.

2021-10-20 11:38 UTC, shuruqt1000 commented
good comments 
completed

2021-10-20 11:38 UTC, closed without merging