done.
Tuwaiq-jed-kot2/HW-Week2_Day03_Inheritance_and_ClassTypes pull request #9
Opened 2021-10-19 20:47 UTC by shahad197

2021-10-19 21:34 UTC, shuruqt1000 commented
please re-do your comments you didn't explain (what the code dose!) not what you wrote

2021-10-19 21:45 UTC, shuruqt1000 requested changes
explain you code explain what each function dose and how you pass values if any and why

2021-10-20 07:02 UTC, shuruqt1000 requested changes

2021-10-20 07:02 UTC, shuruqt1000 commented on HW-Week2_Day03_Inheritance_and_ClassTypes.iml
> +    }
why are these open functions ?

2021-10-20 07:02 UTC, shuruqt1000 commented on HW-Week2_Day03_Inheritance_and_ClassTypes.iml
> +        return (base*height)/2                   /// this is the three sub class amd a made a calculation
why did you do override to this ?

2021-10-20 07:02 UTC, shuruqt1000 commented on HW-Week2_Day03_Inheritance_and_ClassTypes.iml
> +
what do you mean by value X 
what's the function X ?

2021-10-20 15:41 UTC, shahad197 commented on HW-Week2_Day03_Inheritance_and_ClassTypes.iml
> +    }
عشان نورثها للسب كلاسس

2021-10-20 15:42 UTC, shahad197 commented on HW-Week2_Day03_Inheritance_and_ClassTypes.iml
> +        return (base*height)/2                   /// this is the three sub class amd a made a calculation
عشان قانون المساحة يختلف من شكل الى شكل اخر

2021-10-20 15:45 UTC, shahad197 commented on HW-Week2_Day03_Inheritance_and_ClassTypes.iml
> +
i print the function  computeArea from Triangle  class

2021-10-21 10:49 UTC, shuruqt1000 commented
completed

2021-10-21 10:49 UTC, closed without merging